create table public.profiles (
    id uuid not null,
    inserted_at timestamp with time zone not null default timezone ('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
    username text not null,
    constraint profiles_pkey primary key (id),
    constraint profiles_username_key unique (username),
    constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade
) tablespace pg_default;
create table public.cosplay_projects (
    id bigint generated by default as identity not null,
    inserted_at timestamp with time zone not null default timezone ('utc'::text, now()),
    updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
    title text not null,
    character text not null,
    origin text not null,
    image text null,
    current_stage public.stage not null,
    current_visibility public.visibility not null,
    profile uuid not null,
    prerequisites array null,
    constraint cosplay_projects_pkey primary key (id),
    constraint cosplay_projects_profile_fkey foreign key (profile) references profiles (id) on delete cascade
) tablespace pg_default;